#!/usr/bin/python
from random import randint
import random


class Char:
    def __init__(self):
        self.name = ""
        self.health = 1000

    def damage(self, Enemy):
        print "Attack Time"
        print "Health ", Enemy.finalmonster


        chardamage = randint(0, self.health)

        if chardamage == 0:
            print "%s evades %s's attack" % (monsters.name, self.name)
        else:
            print "%s hurts %s" % (self.name, monsters.name)
        return monsterhealth <= 0

class Enemy(Char):
    def __init__(self):
        Char.__init__(self)
        print "Get Ready"
        ## Self instance to call Selectmonster to continue battle
        self.monsterhealth = self.selectmonster()

    def selectmonster(self):
        ## Monsters List
        monsters = ['Goblin', 'Dragon', 'Swordsman', 'Archers', 'Axemen', 'Infantry']
        print monsters

        # Select random monster from list
        monsters = random.choice(monsters)

        print "Random", monsters

        # Dict of monster health
        monsterhealth = {
            'Goblin': 500, 'Dragon': 1200, 'Swordsman': 800, 'Archers': 650, 'Axemen': 700, 'Infantry': 900
        }
        print "Monster Health prior: ", monsterhealth

        # iterate through dict, print if monsters match a key
        for key, value in monsterhealth.items():
            if monsters in key:
                print "For Loop ", monsters
                print "For Loop ", value
                # Calls Char Class
                finalmonster = monsters
                finalhealth = value
                print "Final Monster %s and final value %d" % (finalmonster, finalhealth)
                Char.damage(self, finalmonster)

class Player(Char):
    def __init__(self):
        Char.__init__(self)
        self.health = 1000
        self.health_max = 1000

    def quit(self):
        print "%s can't find the way back home and dies." % self.name

    def help(self):
        print Commands.keys()

    def stats(self):
        print "---------Player Stats---------"
        print "Health:", self.health

    def run(self):
        print "---------Run---------"
        pass

    def explore(self):
        print "---------Explore---------"
        pass

    def attack(self):
        print "attacking"
        ## Calls enemy to begin selecting monster
        Enemy()
        print "returning"

    #
    # def enemy_attacks(self, selectmonster):
    #     selectmonster()

Commands = {
    'quit': Player.quit,
    'help': Player.help,
    'stats': Player.stats,
    'run': Player.run,
    'explore': Player.explore,
    'attack': Player.attack
}

p = Player()
p.name = raw_input("Enter Character Name: ")
print "Type help for a list of actions\n"
print "%s, lets begin..." % p.name

while (p.health > 0):
    line = raw_input("> ")
    if line in Commands:
        Commands[line](p)
        break
    else:
        print "Doesn't understand"
