#!/usr/bin/python
import paramiko
import time
import socket

with open('ipaddresses.txt', 'r') as f:
    for host in f:
        ip = host.rstrip()
        try:
            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            ssh.connect(ip, username='user', password='password')
            print "Connected - %s" % ip
        except paramiko.BadHostKeyException, e:
            print "Key Mismatch - %s" % ip
        except paramiko.AuthenticationException, e:
            print "Authentication Error - %s" % ip
        except (socket.error, paramiko.ssh_exception.NoValidConnectionsError, paramiko.SSHException), e:
            print "Unable to connect - %s" % ip
