#!/usr/bin/python
import paramiko
import socket, threading

threadlock = threading.Lock()

def worker(ip):
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    try:
        ssh.connect(ip, username='bill', password='password')
        out = "Connected - %s" % ip
    except paramiko.BadHostKeyException, e:
        out = "Key Mismatch - %s" % ip
    except paramiko.AuthenticationException, e:
        out = "Authentication Error - %s" % ip
    except (socket.error, paramiko.ssh_exception.NoValidConnectionsError, paramiko.SSHException), e:
        out = "Unable to connect - %s" % ip

    with threadlock:
        print out

def main():
    threads = []
    with open('ipaddresses.txt', 'r') as f:
        for host in f:
            ip = host.rstrip()
            t = threading.Thread(target=worker, args=(ip,))
            t.start()
            threads.append(t)
    for t in threads:
        t.join()

main()

